services:
  frontend:
    # UNCOMMENT - Local Build
    extends:
      file: ${PATH_BUILD_FRONTEND}/docker-compose.yml
      service: frontend
    build:
      context: "${PATH_BUILD_FRONTEND}"
      target: development
    # UNCOMMENT - Local Build
    image: "${PATH_IMAGE_FRONTEND}"
    environment:
      LISTEN_PORT: 3000
      LISTEN_ADDRESS: '0.0.0.0'
      DATABASE_URL: http://database_container:3000
      USERMANAGEMENT_URL: http://user_container:3000
      LOCAL_GAMESERVER_URL: "${LOCAL_IP}"
    ports:
      - "8000:3000"
    tty: false

  user-management:
    # UNCOMMENT - Local Build
    extends:
      file: ${PATH_BUILD_USERMANAGEMENT}/docker-compose.yml
      service: user-management
    build:
      context: "${PATH_BUILD_USERMANAGEMENT}"
      target: development
  # UNCOMMENT - Local Build
    image: "${PATH_IMAGE_USERMANAGEMENT}"
    environment:
      LISTEN_PORT: 3000
      LISTEN_ADDRESS: '0.0.0.0'
      DATABASE_URL: http://database_container:3000
    ports:
      - "8001:3000"
    tty: false

  database:
    # UNCOMMENT - Local Build
    extends:
      file: ${PATH_BUILD_DATABASE}/docker-compose.yml
      service: database
    build:
      context: "${PATH_BUILD_DATABASE}"
      target: development
  # UNCOMMENT - Local Build
    image: "${PATH_IMAGE_DATABASE}"
    environment:
      LISTEN_PORT: 3000
      LISTEN_ADDRESS: '0.0.0.0'
      DATABASE_URL: "file:/app/src/database/database.db"
    ports:
      - "8002:3000"
    tty: false

  gameserver:
    # UNCOMMENT - Local Build
    extends:
      file: ${PATH_BUILD_GAMESERVER}/docker-compose.yml
      service: gameserver
    build:
      context: "${PATH_BUILD_GAMESERVER}"
      target: development
  # UNCOMMENT - Local Build
    image: "${PATH_IMAGE_GAMESERVER}"
    environment:
      LISTEN_PORT: 3000
      LISTEN_ADDRESS: '0.0.0.0'
      DATABASE_URL: http://database_container:3000
      USERMANAGEMENT_URL: http://user_container:3000
    ports:
      - "8003:3000"
    tty: false

volumes:
  database_data:

