services:
  frontend:

    # UNCOMMENT - Local Build
    # extends:
    #   file: ${PATH_BUILD_FRONTEND}/docker-compose.yml
    #   service: frontend
    # build:
    #   context: "${PATH_BUILD_FRONTEND}"
    #   target: development
    image: "${PATH_IMAGE_FRONTEND}"
    # UNCOMMENT - Local Build

    environment:
      LISTEN_PORT: 3000
      LISTEN_ADDRESS: '0.0.0.0'
    ports:
      - "8000:3000"
    tty: false

  user-management:

    # UNCOMMENT - Local Build
    # extends:
    #   file: ${PATH_BUILD_USERMANAGEMENT}/docker-compose.yml
    #   service: user-management
    # build:
    #   context: "${PATH_BUILD_USERMANAGEMENT}"
    #   target: development
    # UNCOMMENT - Local Build

    image: "${PATH_IMAGE_USERMANAGEMENT}"
    environment:
      LISTEN_PORT: 3000
      LISTEN_ADDRESS: '0.0.0.0'
    ports:
      - "8001:3000"
    tty: false

  database:

    # UNCOMMENT - Local Build
    # extends:
    #   file: ${PATH_BUILD_DATABASE}/docker-compose.yml
    #   service: database
    # build:
    #   context: "${PATH_BUILD_DATABASE}"
    #   target: development
    # UNCOMMENT - Local Build

    image: "${PATH_IMAGE_DATABASE}"
    environment:
      LISTEN_PORT: 3000
      LISTEN_ADDRESS: '0.0.0.0'
    ports:
      - "8002:3000"
    tty: false

volumes:
  database_data:

