services:
  frontend:
    ${CONFIG_STR_FRONTEND}
    build:
      context: "${PATH_BUILD_FRONTEND}"
      target: development
    image: ${PATH_IMAGE_FRONTEND}
    environment:
      LISTEN_PORT: 3000
      LISTEN_ADDRESS: '0.0.0.0'
    ports:
      - "8000:3000"

  user-management:
    ${CONFIG_STR_USER_MANAGEMENT}
    build:
      context: "${PATH_BUILD_USER_MANAGEMENT}"
      target: development
    image: ${PATH_IMAGE_USER_MANAGEMENT}
    environment:
      LISTEN_PORT: 3001
      LISTEN_ADDRESS: '0.0.0.0'
    ports:
      - "8001:3001"
