services:
  frontend:
    ${CONFIG_STR}
    build:
      context: ${PATH_BUILD_FRONTEND}
      # The only instance were we'd wanna run it in dev mode would be when running locally.
      target: development
    image: ${PATH_IMAGE_FRONTEND}
    environment:
      LISTEN_PORT: 3000
      LISTEN_ADDRESS: '0.0.0.0'
    ports:
      - "8000:3000"
